config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [ :new, :create, :show, :index ] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: {in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true
  validates :rating, numericality: true
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_param)
    @restaurant.save
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_param
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to "La Fourchette", restaurants_path, class: "navbar-brand" %>
        <%= link_to "New Restaurant", new_restaurant_path, class: "navbar-brand" %>
      </div>
    </nav>
      <div style="margin-top: 120px">
        <%= yield %>
      </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
    <% @restaurants.each do |restaurant| %>
      <div class="box">
        <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
        <p><%= restaurant.address %></p>
        <p><%= restaurant.category %></p>
      </div>
    <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="box">
    <%= simple_form_for (@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :category %>
      <%= f.submit "Submit review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="box">
    <ul class="list-group">
      <h4><%= @restaurant.name %></h4>
      <% @restaurant.reviews.each do |review| %>
        <p>Reviews:</p><li class="list-group-item"><%= review.content %></li>
      <% end %>
      <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>
    </ul>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="box">
    <%= simple_form_for [ @restaurant, @review ] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit "Submit review", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>